import { formatDate, formatDateLong, formatCurrency, todayString } from "./format.js";

/**
 * Format nilai sel sesuai tipe data untuk Excel, CSV, dan PDF:
 * - Harga/biaya dikonversi ke Rupiah
 * - Tanggal ISO dikonversi ke format tanggal Indonesia konsisten
 * - Boolean dikonversi ke label jelas
 */
function formatCellValue(headerLabel, val) {
  if (val === null || val === undefined || val === "") return "-";
  const labelLower = String(headerLabel).toLowerCase();
  if (typeof val === "number" && (labelLower.includes("harga") || labelLower.includes("price") || labelLower.includes("biaya"))) {
    return formatCurrency(val);
  }
  if (typeof val === "string" && /^\d{4}-\d{2}-\d{2}/.test(val)) {
    return formatDate(val);
  }
  if (typeof val === "boolean") {
    return val ? "Aktif" : "Nonaktif";
  }
  return String(val);
}

/**
 * Export data ke Excel (.xlsx), CSV (.csv), atau PDF (.pdf).
 * `rows` harus sudah berupa data yang terfilter di layar, sehingga hasil export
 * selalu mengikuti search/filter/status/tanggal yang sedang aktif.
 *
 * columns: [{ label, value: (row) => string|number }]
 * filters: array string ringkasan filter aktif, ditulis pada header file.
 */
export async function exportRows({ format, name, title, columns, rows, filters = [] }) {
  if (!rows || !rows.length) {
    throw new Error("Tidak ada data untuk diekspor dengan filter saat ini.");
  }

  const stamp = todayString();
  const exportDateStr = formatDateLong(new Date());
  const base = `CariKostKita_${name}_${stamp}`;
  const header = columns.map((c) => c.label);
  const body = rows.map((row) =>
    columns.map((c) => {
      const raw = c.value(row);
      return formatCellValue(c.label, raw);
    })
  );

  /* ===================== CSV (.csv) ===================== */
  if (format === "csv") {
    const BOM = "\uFEFF";
    const escapeCsv = (str) => {
      const s = String(str ?? "").replace(/"/g, '""');
      return `"${s}"`;
    };
    const csvRows = [
      ["# CARIKOSTKITA ADMIN REPORT", title],
      ["# Tanggal Export", exportDateStr],
      ["# Total Data", `${rows.length} Data`],
      ...(filters && filters.length ? [["# Filter Aktif", filters.join(" | ")]] : []),
      [],
      header,
      ...body,
    ];
    const csvContent = BOM + csvRows.map((r) => r.map(escapeCsv).join(",")).join("\r\n");
    const blob = new Blob([csvContent], { type: "text/csv;charset=utf-8;" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${base}.csv`;
    a.click();
    URL.revokeObjectURL(url);
    return `${base}.csv`;
  }

  /* ===================== EXCEL (.xlsx) ===================== */
  if (format === "xlsx") {
    const XLSX = await import("xlsx");

    // Header metadata terstruktur dan profesional
    const meta = [
      ["CARIKOSTKITA ADMIN PANEL"],
      [`Laporan: ${title}`],
      [],
      ["Tanggal Export", `: ${exportDateStr}`],
      ["Total Data", `: ${rows.length} Data`],
    ];

    if (filters && filters.length > 0) {
      filters.forEach((f) => {
        if (f.includes(":")) {
          const [k, ...v] = f.split(":");
          meta.push([k.trim(), `: ${v.join(":").trim()}`]);
        } else {
          meta.push(["Filter", `: ${f}`]);
        }
      });
    } else {
      meta.push(["Filter", ": Semua Data"]);
    }
    meta.push([]); // baris kosong sebelum tabel

    // Baris footer
    const footer = [[], ["Generated by CariKostKita Admin Panel"]];

    const allData = [...meta, header, ...body, ...footer];
    const sheet = XLSX.utils.aoa_to_sheet(allData);

    // Hitung lebar kolom otomatis dengan padding yang nyaman
    sheet["!cols"] = header.map((h, i) => {
      const maxContentLen = Math.max(
        h.length,
        ...body.map((r) => String(r[i] ?? "").length)
      );
      return { wch: Math.min(50, Math.max(14, maxContentLen + 3)) };
    });

    // Freeze header baris tabel (header berada pada baris meta.length + 1)
    sheet["!views"] = [{ state: "frozen", ySplit: meta.length + 1 }];

    const book = XLSX.utils.book_new();
    const cleanSheetName = title.slice(0, 31).replace(/[\\/?*[\]:]/g, " ");
    XLSX.utils.book_append_sheet(book, sheet, cleanSheetName);
    XLSX.writeFile(book, `${base}.xlsx`);
    return `${base}.xlsx`;
  }

  /* ===================== PDF (.pdf) ===================== */
  const { jsPDF } = await import("jspdf");
  const autoTable = (await import("jspdf-autotable")).default;

  const isWide = header.length > 6;
  const doc = new jsPDF({
    orientation: isWide ? "landscape" : "portrait",
    unit: "pt",
    format: "a4",
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const marginLeft = 36;
  const marginRight = 36;
  const contentWidth = pageWidth - marginLeft - marginRight;

  // Header Brand & Title
  doc.setFont("helvetica", "bold");
  doc.setFontSize(16);
  doc.setTextColor(109, 8, 8); // Maroon
  doc.text("CARIKOSTKITA", marginLeft, 40);

  doc.setFontSize(9);
  doc.setTextColor(168, 120, 47); // Gold accent
  doc.text("ADMIN REPORT", marginLeft, 52);

  doc.setFontSize(13);
  doc.setTextColor(33, 29, 26); // Ink
  doc.text(`Laporan: ${title}`, marginLeft, 68);

  // Garis aksen pemisah header
  doc.setDrawColor(109, 8, 8);
  doc.setLineWidth(1.5);
  doc.line(marginLeft, 74, marginLeft + 60, 74);

  // Metadata Box
  doc.setFillColor(251, 248, 238); // Paper
  doc.setDrawColor(216, 208, 187); // Line
  doc.setLineWidth(0.6);
  doc.roundedRect(marginLeft, 80, contentWidth, 34, 4, 4, "FD");

  doc.setFont("helvetica", "normal");
  doc.setFontSize(8.5);
  doc.setTextColor(112, 104, 97); // Muted
  doc.text(`Tanggal Export: `, marginLeft + 10, 94);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(33, 29, 26);
  doc.text(exportDateStr, marginLeft + 72, 94);

  doc.setFont("helvetica", "normal");
  doc.setTextColor(112, 104, 97);
  doc.text(`Total Data: `, marginLeft + 210, 94);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(33, 29, 26);
  doc.text(`${rows.length} Data`, marginLeft + 258, 94);

  const filterSummary = filters && filters.length ? filters.join("  |  ") : "Semua Data";
  doc.setFont("helvetica", "normal");
  doc.setTextColor(112, 104, 97);
  doc.text(`Filter Aktif: `, marginLeft + 10, 107);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(109, 8, 8);
  doc.text(filterSummary, marginLeft + 72, 107, {
    maxWidth: contentWidth - 80,
  });

  // Tabel Dokumen
  autoTable(doc, {
    head: [header],
    body: body.map((r) => r.map(String)),
    startY: 122,
    showHead: "everyPage",
    styles: {
      font: "helvetica",
      fontSize: 8,
      cellPadding: 5,
      textColor: [33, 29, 26],
      lineColor: [216, 208, 187],
      lineWidth: 0.4,
      overflow: "linebreak",
      valign: "middle",
    },
    headStyles: {
      fillColor: [109, 8, 8],
      textColor: [238, 234, 215],
      fontStyle: "bold",
      fontSize: 8.5,
      halign: "left",
      cellPadding: 6,
    },
    alternateRowStyles: {
      fillColor: [251, 248, 238],
    },
    margin: {
      left: marginLeft,
      right: marginRight,
      bottom: 40,
    },
  });

  // Footer di setiap halaman: "Page X of Y"
  const totalPages = doc.getNumberOfPages();
  for (let i = 1; i <= totalPages; i += 1) {
    doc.setPage(i);

    // Garis pemisah footer
    doc.setDrawColor(216, 208, 187);
    doc.setLineWidth(0.5);
    doc.line(marginLeft, pageHeight - 24, pageWidth - marginRight, pageHeight - 24);

    doc.setFont("helvetica", "normal");
    doc.setFontSize(7.5);
    doc.setTextColor(112, 104, 97);

    // Left info
    doc.text(`CariKostKita Admin Panel  •  Generated on ${exportDateStr}`, marginLeft, pageHeight - 12);

    // Right info (Page X of Y)
    doc.text(`Halaman ${i} dari ${totalPages}`, pageWidth - marginRight, pageHeight - 12, {
      align: "right",
    });
  }

  doc.save(`${base}.pdf`);
  return `${base}.pdf`;
}
